// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace JahanAraShop.Areas.Admin.Controllers
{
    public partial class PanelController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PanelController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PanelController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SlideShow()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SlideShow);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveNews()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveNews);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteNews()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteNews);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetInvoiceReport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetInvoiceReport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SaveDiscountcode()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDiscountcode);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PanelController Actions { get { return MVC.Admin.Panel; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Panel";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Panel";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SlidShow = "SlidShow";
            public readonly string SlideShow = "SlideShow";
            public readonly string News = "News";
            public readonly string SaveNews = "SaveNews";
            public readonly string DeleteNews = "DeleteNews";
            public readonly string InvoiceList = "InvoiceList";
            public readonly string GetInvoiceReport = "GetInvoiceReport";
            public readonly string CreateDiscountcode = "CreateDiscountcode";
            public readonly string SaveDiscountcode = "SaveDiscountcode";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SlidShow = "SlidShow";
            public const string SlideShow = "SlideShow";
            public const string News = "News";
            public const string SaveNews = "SaveNews";
            public const string DeleteNews = "DeleteNews";
            public const string InvoiceList = "InvoiceList";
            public const string GetInvoiceReport = "GetInvoiceReport";
            public const string CreateDiscountcode = "CreateDiscountcode";
            public const string SaveDiscountcode = "SaveDiscountcode";
        }


        static readonly ActionParamsClass_SlideShow s_params_SlideShow = new ActionParamsClass_SlideShow();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SlideShow SlideShowParams { get { return s_params_SlideShow; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SlideShow
        {
            public readonly string model = "model";
            public readonly string imgFa = "imgFa";
        }
        static readonly ActionParamsClass_SaveNews s_params_SaveNews = new ActionParamsClass_SaveNews();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveNews SaveNewsParams { get { return s_params_SaveNews; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveNews
        {
            public readonly string model = "model";
            public readonly string imgFa = "imgFa";
        }
        static readonly ActionParamsClass_DeleteNews s_params_DeleteNews = new ActionParamsClass_DeleteNews();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteNews DeleteNewsParams { get { return s_params_DeleteNews; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteNews
        {
            public readonly string Id = "Id";
        }
        static readonly ActionParamsClass_GetInvoiceReport s_params_GetInvoiceReport = new ActionParamsClass_GetInvoiceReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetInvoiceReport GetInvoiceReportParams { get { return s_params_GetInvoiceReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetInvoiceReport
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SaveDiscountcode s_params_SaveDiscountcode = new ActionParamsClass_SaveDiscountcode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDiscountcode SaveDiscountcodeParams { get { return s_params_SaveDiscountcode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDiscountcode
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CreateDiscountcode = "CreateDiscountcode";
                public readonly string InvoiceList = "InvoiceList";
                public readonly string News = "News";
                public readonly string SlidShow = "SlidShow";
            }
            public readonly string CreateDiscountcode = "~/Areas/Admin/Views/Panel/CreateDiscountcode.cshtml";
            public readonly string InvoiceList = "~/Areas/Admin/Views/Panel/InvoiceList.cshtml";
            public readonly string News = "~/Areas/Admin/Views/Panel/News.cshtml";
            public readonly string SlidShow = "~/Areas/Admin/Views/Panel/SlidShow.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PanelController : JahanAraShop.Areas.Admin.Controllers.PanelController
    {
        public T4MVC_PanelController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SlidShowOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SlidShow()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SlidShow);
            SlidShowOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SlideShowOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, JahanAraShop.Areas.Admin.Models.SlideShowViewModel model, System.Web.HttpPostedFileBase imgFa);

        [NonAction]
        public override System.Web.Mvc.ActionResult SlideShow(JahanAraShop.Areas.Admin.Models.SlideShowViewModel model, System.Web.HttpPostedFileBase imgFa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SlideShow);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "imgFa", imgFa);
            SlideShowOverride(callInfo, model, imgFa);
            return callInfo;
        }

        [NonAction]
        partial void NewsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult News()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.News);
            NewsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveNewsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, JahanAraShop.Areas.Admin.Models.NewsViewModel model, System.Web.HttpPostedFileBase imgFa);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveNews(JahanAraShop.Areas.Admin.Models.NewsViewModel model, System.Web.HttpPostedFileBase imgFa)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveNews);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "imgFa", imgFa);
            SaveNewsOverride(callInfo, model, imgFa);
            return callInfo;
        }

        [NonAction]
        partial void DeleteNewsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteNews(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteNews);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            DeleteNewsOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void InvoiceListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult InvoiceList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InvoiceList);
            InvoiceListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetInvoiceReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, JahanAraShop.Areas.Admin.Models.InvoiceReportModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetInvoiceReport(JahanAraShop.Areas.Admin.Models.InvoiceReportModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetInvoiceReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            GetInvoiceReportOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CreateDiscountcodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateDiscountcode()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateDiscountcode);
            CreateDiscountcodeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveDiscountcodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<JahanAraShop.Areas.Admin.Models.DisCodlist> model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SaveDiscountcode(System.Collections.Generic.List<JahanAraShop.Areas.Admin.Models.DisCodlist> model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDiscountcode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveDiscountcodeOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
