// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly AdminClass s_Admin = new AdminClass();
    public static AdminClass Admin { get { return s_Admin; } }
    public static JahanAraShop.Controllers.AccountController Account = new JahanAraShop.Controllers.T4MVC_AccountController();
    public static JahanAraShop.Controllers.Bank.GatewayController Gateway = new JahanAraShop.Controllers.Bank.T4MVC_GatewayController();
    public static JahanAraShop.Controllers.Bank.PaymentController Payment = new JahanAraShop.Controllers.Bank.T4MVC_PaymentController();
    public static JahanAraShop.Controllers.HomeController Home = new JahanAraShop.Controllers.T4MVC_HomeController();
    public static JahanAraShop.Controllers.MessageController Message = new JahanAraShop.Controllers.T4MVC_MessageController();
    public static JahanAraShop.Controllers.NewsController News = new JahanAraShop.Controllers.T4MVC_NewsController();
    public static JahanAraShop.Controllers.ProductController Product = new JahanAraShop.Controllers.T4MVC_ProductController();
    public static JahanAraShop.Controllers.ShopController Shop = new JahanAraShop.Controllers.T4MVC_ShopController();
    public static JahanAraShop.Controllers.UserController User = new JahanAraShop.Controllers.T4MVC_UserController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdminClass
    {
        public readonly string Name = "Admin";
        public JahanAraShop.Areas.Admin.Controllers.AccountController Account = new JahanAraShop.Areas.Admin.Controllers.T4MVC_AccountController();
        public JahanAraShop.Areas.Admin.Controllers.DefaultController Default = new JahanAraShop.Areas.Admin.Controllers.T4MVC_DefaultController();
        public JahanAraShop.Areas.Admin.Controllers.PanelController Panel = new JahanAraShop.Areas.Admin.Controllers.T4MVC_PanelController();
        public JahanAraShop.Areas.Admin.Controllers.SigninController Signin = new JahanAraShop.Areas.Admin.Controllers.T4MVC_SigninController();
        public T4MVC.Admin.SharedController Shared = new T4MVC.Admin.SharedController();
    }
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class css {
            public const string UrlPath = "~/Content/css";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string amaran_min_css = Url("amaran.min.css");
            public static readonly string animate_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/animate.min.css") ? Url("animate.min.css") : Url("animate.css");
            public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
            public static readonly string component_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/component.min.css") ? Url("component.min.css") : Url("component.css");
            public static readonly string font_awesome_animation_min_css = Url("font-awesome-animation.min.css");
            public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
            public static readonly string fractionslider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/fractionslider.min.css") ? Url("fractionslider.min.css") : Url("fractionslider.css");
            public static readonly string full_screen_menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/full-screen-menu.min.css") ? Url("full-screen-menu.min.css") : Url("full-screen-menu.css");
            public static readonly string icofont_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/icofont.min.css") ? Url("icofont.min.css") : Url("icofont.css");
            public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
            public static readonly string lightcase_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/lightcase.min.css") ? Url("lightcase.min.css") : Url("lightcase.css");
            public static readonly string pe_icon_7_stroke_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/pe-icon-7-stroke.min.css") ? Url("pe-icon-7-stroke.min.css") : Url("pe-icon-7-stroke.css");
            public static readonly string PersianDatePicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/PersianDatePicker.min.css") ? Url("PersianDatePicker.min.css") : Url("PersianDatePicker.css");
            public static readonly string PersianDatePicker_min_css = Url("PersianDatePicker.min.css");
            public static readonly string responsive_fa_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive-fa.min.css") ? Url("responsive-fa.min.css") : Url("responsive-fa.css");
            public static readonly string responsive_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/responsive.min.css") ? Url("responsive.min.css") : Url("responsive.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class skin {
                public const string UrlPath = "~/Content/css/skin";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string default_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/default.min.css") ? Url("default.min.css") : Url("default.css");
            }
        
            public static readonly string slick_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/slick-theme.min.css") ? Url("slick-theme.min.css") : Url("slick-theme.css");
            public static readonly string slick_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/slick.min.css") ? Url("slick.min.css") : Url("slick.css");
            public static readonly string slider_360_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/slider-360.min.css") ? Url("slider-360.min.css") : Url("slider-360.css");
            public static readonly string style_fa_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/style-fa.min.css") ? Url("style-fa.min.css") : Url("style-fa.css");
            public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/style.min.css") ? Url("style.min.css") : Url("style.css");
            public static readonly string youtube_pop_up_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/youtube-pop-up.min.css") ? Url("youtube-pop-up.min.css") : Url("youtube-pop-up.css");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            public const string UrlPath = "~/Content/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string fontawesome_webfont_eot = Url("fontawesome-webfont.eot");
            public static readonly string fontawesome_webfont_svg = Url("fontawesome-webfont.svg");
            public static readonly string fontawesome_webfont_ttf = Url("fontawesome-webfont.ttf");
            public static readonly string fontawesome_webfont_woff = Url("fontawesome-webfont.woff");
            public static readonly string fontawesome_webfont_woff2 = Url("fontawesome-webfont.woff2");
            public static readonly string FontAwesome_otf = Url("FontAwesome.otf");
            public static readonly string glyphicons_halflings_regular_eot = Url("glyphicons-halflings-regular.eot");
            public static readonly string glyphicons_halflings_regular_svg = Url("glyphicons-halflings-regular.svg");
            public static readonly string glyphicons_halflings_regular_ttf = Url("glyphicons-halflings-regular.ttf");
            public static readonly string glyphicons_halflings_regular_woff = Url("glyphicons-halflings-regular.woff");
            public static readonly string glyphicons_halflings_regular_woff2 = Url("glyphicons-halflings-regular.woff2");
            public static readonly string icofont_eot = Url("icofont.eot");
            public static readonly string icofont_svg = Url("icofont.svg");
            public static readonly string icofont_ttf = Url("icofont.ttf");
            public static readonly string icofont_woff = Url("icofont.woff");
            public static readonly string lightcase_eot = Url("lightcase.eot");
            public static readonly string lightcase_svg = Url("lightcase.svg");
            public static readonly string lightcase_ttf = Url("lightcase.ttf");
            public static readonly string lightcase_woff = Url("lightcase.woff");
            public static readonly string Pe_icon_7_stroke_eot = Url("Pe-icon-7-stroke.eot");
            public static readonly string Pe_icon_7_stroke_svg = Url("Pe-icon-7-stroke.svg");
            public static readonly string Pe_icon_7_stroke_ttf = Url("Pe-icon-7-stroke.ttf");
            public static readonly string Pe_icon_7_stroke_woff = Url("Pe-icon-7-stroke.woff");
            public static readonly string slick_eot = Url("slick.eot");
            public static readonly string slick_svg = Url("slick.svg");
            public static readonly string slick_ttf = Url("slick.ttf");
            public static readonly string slick_woff = Url("slick.woff");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Yekan {
                public const string UrlPath = "~/Content/fonts/Yekan";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class eof {
                    public const string UrlPath = "~/Content/fonts/Yekan/eof";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string iranyekanwebbold_fanum__eot = Url("iranyekanwebbold(fanum).eot");
                    public static readonly string iranyekanweblight_fanum__eot = Url("iranyekanweblight(fanum).eot");
                    public static readonly string iranyekanwebregular_fanum__eot = Url("iranyekanwebregular(fanum).eot");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class svg {
                    public const string UrlPath = "~/Content/fonts/Yekan/svg";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string iranyekanwebbold_fanum__svg = Url("iranyekanwebbold(fanum).svg");
                    public static readonly string iranyekanweblight_fanum__svg = Url("iranyekanweblight(fanum).svg");
                    public static readonly string iranyekanwebregular_fanum__svg = Url("iranyekanwebregular(fanum).svg");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class ttf {
                    public const string UrlPath = "~/Content/fonts/Yekan/ttf";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string iranyekanwebbold_fanum__ttf = Url("iranyekanwebbold(fanum).ttf");
                    public static readonly string iranyekanweblight_fanum__ttf = Url("iranyekanweblight(fanum).ttf");
                    public static readonly string iranyekanwebregular_fanum__ttf = Url("iranyekanwebregular(fanum).ttf");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class woff {
                    public const string UrlPath = "~/Content/fonts/Yekan/woff";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string iranyekanwebbold_fanum__woff = Url("iranyekanwebbold(fanum).woff");
                    public static readonly string iranyekanweblight_fanum__woff = Url("iranyekanweblight(fanum).woff");
                    public static readonly string iranyekanwebregular_fanum__woff = Url("iranyekanwebregular(fanum).woff");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class woff2 {
                    public const string UrlPath = "~/Content/fonts/Yekan/woff2";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string iranyekanwebbold_fanum__woff2 = Url("iranyekanwebbold(fanum).woff2");
                    public static readonly string iranyekanweblight_fanum__woff2 = Url("iranyekanweblight(fanum).woff2");
                    public static readonly string iranyekanwebregular_fanum__woff2 = Url("iranyekanwebregular(fanum).woff2");
                }
            
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            public const string UrlPath = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string _360_png = Url("360.png");
            public static readonly string _404_png = Url("404.png");
            public static readonly string about_banner_jpg = Url("about-banner.jpg");
            public static readonly string apple_jpg = Url("apple.jpg");
            public static readonly string armin_jpg = Url("armin.jpg");
            public static readonly string athr_fig_bg_png = Url("athr-fig-bg.png");
            public static readonly string blog_align_right_jpg = Url("blog-align-right.jpg");
            public static readonly string blog_big1_jpg = Url("blog-big1.jpg");
            public static readonly string blog_big2_jpg = Url("blog-big2.jpg");
            public static readonly string blog_big3_jpg = Url("blog-big3.jpg");
            public static readonly string blog_big4_jpg = Url("blog-big4.jpg");
            public static readonly string blog_big5_jpg = Url("blog-big5.jpg");
            public static readonly string blog_big6_jpg = Url("blog-big6.jpg");
            public static readonly string blog_featured_jpg = Url("blog-featured.jpg");
            public static readonly string blog_med_1_jpg = Url("blog-med-1.jpg");
            public static readonly string blog_med_2_jpg = Url("blog-med-2.jpg");
            public static readonly string blog_med_3_jpg = Url("blog-med-3.jpg");
            public static readonly string blog_med_4_jpg = Url("blog-med-4.jpg");
            public static readonly string blog_med_5_jpg = Url("blog-med-5.jpg");
            public static readonly string blog_med_6_jpg = Url("blog-med-6.jpg");
            public static readonly string blog_modern_big1_jpg = Url("blog-modern-big1.jpg");
            public static readonly string blog_modern_big2_jpg = Url("blog-modern-big2.jpg");
            public static readonly string blog_modern_big3_jpg = Url("blog-modern-big3.jpg");
            public static readonly string blog_modern_big4_jpg = Url("blog-modern-big4.jpg");
            public static readonly string blog_modern_big5_jpg = Url("blog-modern-big5.jpg");
            public static readonly string blog_modern_big6_jpg = Url("blog-modern-big6.jpg");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Branchs {
                public const string UrlPath = "~/Content/images/Branchs";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            public static readonly string canon_jpg = Url("canon.jpg");
            public static readonly string cart_pdt_thumb1_jpg = Url("cart-pdt-thumb1.jpg");
            public static readonly string cart_pdt_thumb2_jpg = Url("cart-pdt-thumb2.jpg");
            public static readonly string cart_pdt_thumb3_jpg = Url("cart-pdt-thumb3.jpg");
            public static readonly string cart_pdt_thumb4_jpg = Url("cart-pdt-thumb4.jpg");
            public static readonly string cat_bag_jpg = Url("cat-bag.jpg");
            public static readonly string cat_glasses_jpg = Url("cat-glasses.jpg");
            public static readonly string cat_shoes_jpg = Url("cat-shoes.jpg");
            public static readonly string cat_smart_accessories_jpg = Url("cat-smart-accessories.jpg");
            public static readonly string cat_smart_phone_jpg = Url("cat-smart-phone.jpg");
            public static readonly string cat_smart_watch_jpg = Url("cat-smart-watch.jpg");
            public static readonly string check_out_paypal_jpg = Url("check-out-paypal.jpg");
            public static readonly string cmnt_athr_jpg = Url("cmnt-athr.jpg");
            public static readonly string cmnt_athr1_jpg = Url("cmnt-athr1.jpg");
            public static readonly string cmnt_athr2_jpg = Url("cmnt-athr2.jpg");
            public static readonly string cmnt_athr3_jpg = Url("cmnt-athr3.jpg");
            public static readonly string contact_banner_jpg = Url("contact-banner.jpg");
            public static readonly string ele_sub_cat_offer_jpg = Url("ele-sub-cat-offer.jpg");
            public static readonly string ele_sub_mobile_offer_jpg = Url("ele-sub-mobile-offer.jpg");
            public static readonly string fav_png = Url("fav.png");
            public static readonly string flag1_png = Url("flag1.png");
            public static readonly string headphone_png = Url("headphone.png");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class home {
                public const string UrlPath = "~/Content/images/home";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string ajax_loader_gif = Url("ajax-loader.gif");
                public static readonly string cat_acc_jpg = Url("cat-acc.jpg");
                public static readonly string cat_ladies_jpg = Url("cat-ladies.jpg");
                public static readonly string cat_mens_jpg = Url("cat-mens.jpg");
                public static readonly string cat_summer_jpg = Url("cat-summer.jpg");
                public static readonly string col1_png = Url("col1.png");
                public static readonly string col2_png = Url("col2.png");
                public static readonly string col3_png = Url("col3.png");
                public static readonly string col4_png = Url("col4.png");
                public static readonly string fs_pager_png = Url("fs.pager.png");
                public static readonly string fs_prevnext_png = Url("fs.prevnext.png");
                public static readonly string fs_spinner_gif = Url("fs.spinner.gif");
            }
        
            public static readonly string htc_jpg = Url("htc.jpg");
            public static readonly string insta_1_jpg = Url("insta-1.jpg");
            public static readonly string insta_2_jpg = Url("insta-2.jpg");
            public static readonly string insta_3_jpg = Url("insta-3.jpg");
            public static readonly string insta_4_jpg = Url("insta-4.jpg");
            public static readonly string insta_5_jpg = Url("insta-5.jpg");
            public static readonly string insta_6_jpg = Url("insta-6.jpg");
            public static readonly string insta_7_jpg = Url("insta-7.jpg");
            public static readonly string landing_bg_jpg = Url("landing-bg.jpg");
            public static readonly string lg_jpg = Url("lg.jpg");
            public static readonly string Loading_gif = Url("Loading.gif");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Logo {
                public const string UrlPath = "~/Content/images/Logo";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string _24_png = Url("24.png");
                public static readonly string logo_png = Url("logo.png");
                public static readonly string LogoJahanAra_png = Url("LogoJahanAra.png");
            }
        
            public static readonly string logo_big_png = Url("logo-big.png");
            public static readonly string logo_png = Url("logo.png");
            public static readonly string logo2_png = Url("logo2.png");
            public static readonly string logo4_png = Url("logo4.png");
            public static readonly string logo5_png = Url("logo5.png");
            public static readonly string look1_jpg = Url("look1.jpg");
            public static readonly string look2_jpg = Url("look2.jpg");
            public static readonly string look3_jpg = Url("look3.jpg");
            public static readonly string man_png = Url("man.png");
            public static readonly string MEN_S_SIZE_CHART_1_jpg = Url("MEN_S-SIZE-CHART_1.jpg");
            public static readonly string mobile_banner_jpg = Url("mobile-banner.jpg");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class News {
                public const string UrlPath = "~/Content/images/News";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string News1_png = Url("News1.png");
                public static readonly string News2_png = Url("News2.png");
                public static readonly string News3_png = Url("News3.png");
                public static readonly string News4_png = Url("News4.png");
                public static readonly string page_title3_jpg = Url("page-title3.jpg");
            }
        
            public static readonly string news1_jpg = Url("news1.jpg");
            public static readonly string news2_jpg = Url("news2.jpg");
            public static readonly string news2_jpg_png = Url("news2.jpg.png");
            public static readonly string news3_jpg = Url("news3.jpg");
            public static readonly string news4_jpg = Url("news4.jpg");
            public static readonly string newsletter_bg_jpg = Url("newsletter-bg.jpg");
            public static readonly string newsletter_bg1_png = Url("newsletter-bg1.png");
            public static readonly string nokia_jpg = Url("nokia.jpg");
            public static readonly string offer_ideapad_jpg = Url("offer-ideapad.jpg");
            public static readonly string offer_iwatch_jpg = Url("offer-iwatch.jpg");
            public static readonly string offer_product_jpg = Url("offer-product.jpg");
            public static readonly string page_title_jpg = Url("page-title.jpg");
            public static readonly string page_title3_jpg = Url("page-title3.jpg");
            public static readonly string parallax1_jpg = Url("parallax1.jpg");
            public static readonly string parallax2_jpg = Url("parallax2.jpg");
            public static readonly string pdt_single_slide1_jpg = Url("pdt-single-slide1.jpg");
            public static readonly string pdt_single_slide2_jpg = Url("pdt-single-slide2.jpg");
            public static readonly string pdt_single_slide3_jpg = Url("pdt-single-slide3.jpg");
            public static readonly string pdt_single_slide4_jpg = Url("pdt-single-slide4.jpg");
            public static readonly string pdt_single_slide5_jpg = Url("pdt-single-slide5.jpg");
            public static readonly string pdt_single_slide6_jpg = Url("pdt-single-slide6.jpg");
            public static readonly string phone1_png = Url("phone1.png");
            public static readonly string product1_jpg = Url("product1.jpg");
            public static readonly string product10_jpg = Url("product10.jpg");
            public static readonly string product11_jpg = Url("product11.jpg");
            public static readonly string product12_jpg = Url("product12.jpg");
            public static readonly string product13_jpg = Url("product13.jpg");
            public static readonly string product14_jpg = Url("product14.jpg");
            public static readonly string product15_jpg = Url("product15.jpg");
            public static readonly string product16_jpg = Url("product16.jpg");
            public static readonly string product17_jpg = Url("product17.jpg");
            public static readonly string product18_jpg = Url("product18.jpg");
            public static readonly string product19_jpg = Url("product19.jpg");
            public static readonly string product2_jpg = Url("product2.jpg");
            public static readonly string product20_jpg = Url("product20.jpg");
            public static readonly string product21_jpg = Url("product21.jpg");
            public static readonly string product3_jpg = Url("product3.jpg");
            public static readonly string product4_jpg = Url("product4.jpg");
            public static readonly string product5_jpg = Url("product5.jpg");
            public static readonly string product6_jpg = Url("product6.jpg");
            public static readonly string product7_jpg = Url("product7.jpg");
            public static readonly string product8_jpg = Url("product8.jpg");
            public static readonly string product9_jpg = Url("product9.jpg");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Products {
                public const string UrlPath = "~/Content/images/Products";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string _010367_png = Url("010367.png");
                public static readonly string _010368_png = Url("010368.png");
                public static readonly string _010369_png = Url("010369.png");
                public static readonly string _06772_png = Url("06772.png");
                public static readonly string _10128_png = Url("10128.png");
                public static readonly string _10264_png = Url("10264.png");
                public static readonly string _3052503155104_png = Url("3052503155104.png");
                public static readonly string _3052503155203_png = Url("3052503155203.png");
                public static readonly string _3052503155302_png = Url("3052503155302.png");
                public static readonly string _3052503155401_png = Url("3052503155401.png");
                public static readonly string _3052503155500_png = Url("3052503155500.png");
                public static readonly string _3052503155609_png = Url("3052503155609.png");
                public static readonly string _3052503155708_png = Url("3052503155708.png");
                public static readonly string _3052503563107_png = Url("3052503563107.png");
                public static readonly string _3052503563206_png = Url("3052503563206.png");
                public static readonly string _3052503563305_png = Url("3052503563305.png");
                public static readonly string _3052503563404_png = Url("3052503563404.png");
                public static readonly string _3052503563503_png = Url("3052503563503.png");
                public static readonly string _3052503563602_png = Url("3052503563602.png");
                public static readonly string _3052503573106_png = Url("3052503573106.png");
                public static readonly string _3052503573205_png = Url("3052503573205.png");
                public static readonly string _3052503573304_png = Url("3052503573304.png");
                public static readonly string _3052503605227_png = Url("3052503605227.png");
                public static readonly string _3052503605524_png = Url("3052503605524.png");
                public static readonly string _3052503605623_png = Url("3052503605623.png");
                public static readonly string _3052503650128_png = Url("3052503650128.png");
                public static readonly string _3052503650227_png = Url("3052503650227.png");
                public static readonly string _3052503650326_png = Url("3052503650326.png");
                public static readonly string _3052503667126_png = Url("3052503667126.png");
                public static readonly string _3052503685106_png = Url("3052503685106.png");
                public static readonly string _3052503685205_png = Url("3052503685205.png");
                public static readonly string _3052503685304_png = Url("3052503685304.png");
                public static readonly string _3052503685403_png = Url("3052503685403.png");
                public static readonly string _3052503685502_png = Url("3052503685502.png");
                public static readonly string _3052503685601_png = Url("3052503685601.png");
                public static readonly string _3052503700106_png = Url("3052503700106.png");
                public static readonly string _3052503705118_png = Url("3052503705118.png");
                public static readonly string _3052503705149_png = Url("3052503705149.png");
                public static readonly string _3052503715100_png = Url("3052503715100.png");
                public static readonly string _3052503715506_png = Url("3052503715506.png");
                public static readonly string _3052503735313_png = Url("3052503735313.png");
                public static readonly string _3052503735412_png = Url("3052503735412.png");
                public static readonly string _3052503735511_png = Url("3052503735511.png");
                public static readonly string _3052503751030_png = Url("3052503751030.png");
                public static readonly string _3052503753331_png = Url("3052503753331.png");
                public static readonly string _3052503753430_png = Url("3052503753430.png");
                public static readonly string _3052503754833_png = Url("3052503754833.png");
                public static readonly string _3052503755434_png = Url("3052503755434.png");
                public static readonly string _3052503757230_png = Url("3052503757230.png");
                public static readonly string _3052503757438_png = Url("3052503757438.png");
                public static readonly string _3052503758534_png = Url("3052503758534.png");
                public static readonly string _3052503759234_png = Url("3052503759234.png");
                public static readonly string _3052503759531_png = Url("3052503759531.png");
                public static readonly string _3052503870106_png = Url("3052503870106.png");
                public static readonly string _3052503870205_png = Url("3052503870205.png");
                public static readonly string _3052503870304_png = Url("3052503870304.png");
                public static readonly string _3052503901503_png = Url("3052503901503.png");
                public static readonly string _3052503901602_png = Url("3052503901602.png");
                public static readonly string _3614222985600_png = Url("3614222985600.png");
                public static readonly string _3614222985617_png = Url("3614222985617.png");
                public static readonly string _3614222985624_png = Url("3614222985624.png");
                public static readonly string _3614222986058_png = Url("3614222986058.png");
                public static readonly string _3614222986065_png = Url("3614222986065.png");
                public static readonly string _3614222986072_png = Url("3614222986072.png");
                public static readonly string _3614222986089_png = Url("3614222986089.png");
                public static readonly string _3614224440534_png = Url("3614224440534.png");
                public static readonly string _3614224440541_png = Url("3614224440541.png");
                public static readonly string _3614224440558_png = Url("3614224440558.png");
                public static readonly string _3614224440565_png = Url("3614224440565.png");
                public static readonly string _3614224440572_png = Url("3614224440572.png");
                public static readonly string _8410412020107_png = Url("8410412020107.png");
                public static readonly string _8410412020138_png = Url("8410412020138.png");
                public static readonly string _8410412020145_png = Url("8410412020145.png");
                public static readonly string _8410412020183_png = Url("8410412020183.png");
                public static readonly string _8410412020213_png = Url("8410412020213.png");
                public static readonly string _8410412020275_png = Url("8410412020275.png");
                public static readonly string _8410412020305_png = Url("8410412020305.png");
                public static readonly string _8410412020329_png = Url("8410412020329.png");
                public static readonly string _8410412020336_png = Url("8410412020336.png");
                public static readonly string _8410412020343_png = Url("8410412020343.png");
                public static readonly string _8410412020350_png = Url("8410412020350.png");
                public static readonly string _8410412020381_png = Url("8410412020381.png");
                public static readonly string _8410412020398_png = Url("8410412020398.png");
                public static readonly string _8410412020411_png = Url("8410412020411.png");
                public static readonly string _8410412020428_png = Url("8410412020428.png");
                public static readonly string _8410412020527_png = Url("8410412020527.png");
                public static readonly string _8410412020534_png = Url("8410412020534.png");
                public static readonly string _8410412020541_png = Url("8410412020541.png");
                public static readonly string _8410412020558_png = Url("8410412020558.png");
                public static readonly string _8410412020565_png = Url("8410412020565.png");
                public static readonly string _8410412020572_png = Url("8410412020572.png");
                public static readonly string _8410412020626_png = Url("8410412020626.png");
                public static readonly string _8410412020688_png = Url("8410412020688.png");
                public static readonly string _8410412020831_png = Url("8410412020831.png");
                public static readonly string _8410412020909_png = Url("8410412020909.png");
                public static readonly string _8410412020916_png = Url("8410412020916.png");
                public static readonly string _8410412020947_png = Url("8410412020947.png");
                public static readonly string _8410412020954_png = Url("8410412020954.png");
                public static readonly string _8410412020961_png = Url("8410412020961.png");
                public static readonly string _8410412021005_png = Url("8410412021005.png");
                public static readonly string _8410412021043_png = Url("8410412021043.png");
                public static readonly string _8410412021074_png = Url("8410412021074.png");
                public static readonly string _8410412021258_png = Url("8410412021258.png");
                public static readonly string _8410412021265_png = Url("8410412021265.png");
                public static readonly string _8410412021272_png = Url("8410412021272.png");
                public static readonly string _8410412021289_png = Url("8410412021289.png");
                public static readonly string _8410412021838_png = Url("8410412021838.png");
                public static readonly string _8410412021845_png = Url("8410412021845.png");
                public static readonly string _8410412022170_png = Url("8410412022170.png");
                public static readonly string _8410412022187_png = Url("8410412022187.png");
                public static readonly string _8410412022231_png = Url("8410412022231.png");
                public static readonly string _8410412022255_png = Url("8410412022255.png");
                public static readonly string _8410412022262_png = Url("8410412022262.png");
                public static readonly string _8410412024112_png = Url("8410412024112.png");
                public static readonly string _8410412024808_png = Url("8410412024808.png");
                public static readonly string _8410412024860_png = Url("8410412024860.png");
                public static readonly string _8410412024877_png = Url("8410412024877.png");
                public static readonly string _8410412024983_png = Url("8410412024983.png");
                public static readonly string _8410412025126_png = Url("8410412025126.png");
                public static readonly string _8410412025133_png = Url("8410412025133.png");
                public static readonly string _8410412025508_png = Url("8410412025508.png");
                public static readonly string _8410412027106_png = Url("8410412027106.png");
                public static readonly string _8410412028066_png = Url("8410412028066.png");
                public static readonly string _8410412028127_png = Url("8410412028127.png");
                public static readonly string _8410412028141_png = Url("8410412028141.png");
                public static readonly string _8410412028158_png = Url("8410412028158.png");
                public static readonly string _8410412028165_png = Url("8410412028165.png");
                public static readonly string _8410412028226_png = Url("8410412028226.png");
                public static readonly string _8410412028233_png = Url("8410412028233.png");
                public static readonly string _8410412028240_png = Url("8410412028240.png");
                public static readonly string _8410412028387_png = Url("8410412028387.png");
                public static readonly string _8410412028417_png = Url("8410412028417.png");
                public static readonly string _8410412028462_png = Url("8410412028462.png");
                public static readonly string _8410412028479_png = Url("8410412028479.png");
                public static readonly string _8410412028523_png = Url("8410412028523.png");
                public static readonly string _8410412028530_png = Url("8410412028530.png");
                public static readonly string _8410412028707_png = Url("8410412028707.png");
                public static readonly string _8410412028714_png = Url("8410412028714.png");
                public static readonly string _8410412028752_png = Url("8410412028752.png");
                public static readonly string _8410412028851_png = Url("8410412028851.png");
                public static readonly string _8410412028882_png = Url("8410412028882.png");
                public static readonly string _8410412028943_png = Url("8410412028943.png");
                public static readonly string _8410412029209_png = Url("8410412029209.png");
                public static readonly string _8410412029490_png = Url("8410412029490.png");
                public static readonly string _8410412029537_png = Url("8410412029537.png");
                public static readonly string _8410412029544_png = Url("8410412029544.png");
                public static readonly string _8410412029551_png = Url("8410412029551.png");
                public static readonly string _8410412029568_png = Url("8410412029568.png");
                public static readonly string _8410412029575_png = Url("8410412029575.png");
                public static readonly string _8410412029636_png = Url("8410412029636.png");
                public static readonly string _8410412029742_png = Url("8410412029742.png");
                public static readonly string _8410412029766_png = Url("8410412029766.png");
                public static readonly string _8410412029773_png = Url("8410412029773.png");
                public static readonly string _8410412029902_png = Url("8410412029902.png");
                public static readonly string _8410412029926_png = Url("8410412029926.png");
                public static readonly string _8410412029933_png = Url("8410412029933.png");
                public static readonly string _8410412047333_png = Url("8410412047333.png");
                public static readonly string _8410412047357_png = Url("8410412047357.png");
                public static readonly string _8410412047364_png = Url("8410412047364.png");
                public static readonly string _8410412047371_png = Url("8410412047371.png");
                public static readonly string _8410412050210_png = Url("8410412050210.png");
                public static readonly string _8410412050234_png = Url("8410412050234.png");
                public static readonly string _8410412057004_png = Url("8410412057004.png");
                public static readonly string _8410412057011_png = Url("8410412057011.png");
                public static readonly string _8410412057042_png = Url("8410412057042.png");
                public static readonly string _8410412059510_png = Url("8410412059510.png");
                public static readonly string _8410412503167_png = Url("8410412503167.png");
                public static readonly string _8410412503198_png = Url("8410412503198.png");
                public static readonly string _8410412504010_png = Url("8410412504010.png");
                public static readonly string _8410412506984_png = Url("8410412506984.png");
                public static readonly string _8410412506991_png = Url("8410412506991.png");
                public static readonly string _8410412507073_png = Url("8410412507073.png");
                public static readonly string _8410412702904_png = Url("8410412702904.png");
                public static readonly string defult_png = Url("defult.png");
            }
        
            public static readonly string promo_banner1_jpg = Url("promo-banner1.jpg");
            public static readonly string promo_banner2_jpg = Url("promo-banner2.jpg");
            public static readonly string quick_view_1_png = Url("quick-view-1.png");
            public static readonly string quick_view_2_png = Url("quick-view-2.png");
            public static readonly string quick_view_3_png = Url("quick-view-3.png");
            public static readonly string quick_view_4_png = Url("quick-view-4.png");
            public static readonly string quick_view_5_png = Url("quick-view-5.png");
            public static readonly string quick_view_6_png = Url("quick-view-6.png");
            public static readonly string sale_girl_png = Url("sale-girl.png");
            public static readonly string samsung_jpg = Url("samsung.jpg");
            public static readonly string scroll_slider_img1_jpg = Url("scroll-slider-img1.jpg");
            public static readonly string scroll_slider_img2_jpg = Url("scroll-slider-img2.jpg");
            public static readonly string scroll_slider_img3_jpg = Url("scroll-slider-img3.jpg");
            public static readonly string select_bg_jpg = Url("select-bg.jpg");
            public static readonly string shop_sidebar_jpg = Url("shop-sidebar.jpg");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class sidebar {
                public const string UrlPath = "~/Content/images/sidebar";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string sidebar_jpg = Url("sidebar.jpg");
            }
        
            public static readonly string size_chart_man_png = Url("size-chart-man.png");
            public static readonly string size_chart_women_png = Url("size-chart-women.png");
            public static readonly string size_chart_jpg = Url("size-chart.jpg");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Slider {
                public const string UrlPath = "~/Content/images/Slider";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string _0181e128_0af0_4f92_8aee_bdac6b8d35d7_jpg = Url("0181e128-0af0-4f92-8aee-bdac6b8d35d7.jpg");
                public static readonly string _9f5ecfd5_59e9_4da7_b127_4d26e8b97657_jpg = Url("9f5ecfd5-59e9-4da7-b127-4d26e8b97657.jpg");
                public static readonly string dfc167ac_a28f_4ae8_aaf6_c3b3c571046f_jpg = Url("dfc167ac-a28f-4ae8-aaf6-c3b3c571046f.jpg");
                public static readonly string e8c5ad59_29da_4522_b65e_5eff27a99eda_jpg = Url("e8c5ad59-29da-4522-b65e-5eff27a99eda.jpg");
                public static readonly string f9681b0c_6687_4ae8_973b_76b21b0d237b_jpg = Url("f9681b0c-6687-4ae8-973b-76b21b0d237b.jpg");
            }
        
            public static readonly string slider1_bg_jpg = Url("slider1-bg.jpg");
            public static readonly string summer_promo_bg_png = Url("summer-promo-bg.png");
            public static readonly string team1_jpg = Url("team1.jpg");
            public static readonly string team2_jpg = Url("team2.jpg");
            public static readonly string team3_jpg = Url("team3.jpg");
            public static readonly string team4_jpg = Url("team4.jpg");
            public static readonly string video_bg_jpg = Url("video-bg.jpg");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class view_360 {
                public const string UrlPath = "~/Content/images/view-360";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            public static readonly string watch_png = Url("watch.png");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class js {
            public const string UrlPath = "~/Content/js";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
            public static readonly string count_up_min_js = Url("count-up.min.js");
            public static readonly string jarallax_video_min_js = Url("jarallax-video.min.js");
            public static readonly string jarallax_min_js = Url("jarallax.min.js");
            public static readonly string jquery_3_2_1_min_js = Url("jquery-3.2.1.min.js");
            public static readonly string jquery_ui_min_js = Url("jquery-ui.min.js");
            public static readonly string jquery_amaran_min_js = Url("jquery.amaran.min.js");
            public static readonly string jquery_countdown_min_js = Url("jquery.countdown.min.js");
            public static readonly string jquery_fractionslider_min_js = Url("jquery.fractionslider.min.js");
            public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
            public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
            public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
            public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
            public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
            public static readonly string jquery_waypoints_min_js = Url("jquery.waypoints.min.js");
            public static readonly string js_cookie_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/js.cookie.min.js") ? Url("js.cookie.min.js") : Url("js.cookie.js");
            public static readonly string lightcase_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/lightcase.min.js") ? Url("lightcase.min.js") : Url("lightcase.js");
            public static readonly string main_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/main.min.js") ? Url("main.min.js") : Url("main.js");
            public static readonly string masonry_pkgd_min_js = Url("masonry.pkgd.min.js");
            public static readonly string PersianDatePicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/PersianDatePicker.min.js") ? Url("PersianDatePicker.min.js") : Url("PersianDatePicker.js");
            public static readonly string PersianDatePicker_min_js = Url("PersianDatePicker.min.js");
            public static readonly string slick_min_js = Url("slick.min.js");
            public static readonly string threesixty_min_js = Url("threesixty.min.js");
            public static readonly string touch_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/touch.min.js") ? Url("touch.min.js") : Url("touch.js");
            public static readonly string youtube_jquery_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/youtube-jquery.min.js") ? Url("youtube-jquery.min.js") : Url("youtube-jquery.js");
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Content 
        {
            public static partial class css 
            {
                public static partial class skin 
                {
                    public static class Assets
                    {
                        public static readonly string default_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/skin/default.css");
                    }
                }
                public static class Assets
                {
                    public static readonly string amaran_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/amaran.min.css");
                    public static readonly string animate_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/animate.css");
                    public static readonly string bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/bootstrap.min.css");
                    public static readonly string component_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/component.css");
                    public static readonly string font_awesome_animation_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/font-awesome-animation.min.css");
                    public static readonly string font_awesome_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/font-awesome.min.css");
                    public static readonly string fractionslider_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/fractionslider.css");
                    public static readonly string full_screen_menu_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/full-screen-menu.css");
                    public static readonly string icofont_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/icofont.css");
                    public static readonly string jquery_ui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/jquery-ui.min.css");
                    public static readonly string lightcase_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/lightcase.css");
                    public static readonly string pe_icon_7_stroke_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/pe-icon-7-stroke.css");
                    public static readonly string PersianDatePicker_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/PersianDatePicker.css");
                    public static readonly string PersianDatePicker_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/PersianDatePicker.min.css");
                    public static readonly string responsive_fa_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/responsive-fa.css");
                    public static readonly string responsive_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/responsive.css");
                    public static readonly string slick_theme_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/slick-theme.css");
                    public static readonly string slick_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/slick.css");
                    public static readonly string slider_360_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/slider-360.css");
                    public static readonly string style_fa_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/style-fa.css");
                    public static readonly string style_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/style.css");
                    public static readonly string youtube_pop_up_css = T4MVCHelpers.ProcessAssetPath("~/Content/css/youtube-pop-up.css");
                }
            }
            public static partial class fonts 
            {
                public static partial class Yekan 
                {
                    public static partial class eof 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class svg 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class ttf 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class woff 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class woff2 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class images 
            {
                public static partial class Branchs 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class home 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Logo 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class News 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Products 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class sidebar 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class Slider 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class view_360 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class js 
            {
                public static class Assets
                {
                    public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/bootstrap.min.js"); 
                    public static readonly string count_up_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/count-up.min.js"); 
                    public static readonly string jarallax_video_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jarallax-video.min.js"); 
                    public static readonly string jarallax_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jarallax.min.js"); 
                    public static readonly string jquery_3_2_1_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery-3.2.1.min.js"); 
                    public static readonly string jquery_ui_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery-ui.min.js"); 
                    public static readonly string jquery_amaran_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.amaran.min.js"); 
                    public static readonly string jquery_countdown_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.countdown.min.js"); 
                    public static readonly string jquery_fractionslider_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.fractionslider.min.js"); 
                    public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.validate.js"); 
                    public static readonly string jquery_validate_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.validate.min.js"); 
                    public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.validate.unobtrusive.js"); 
                    public static readonly string jquery_validate_unobtrusive_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.validate.unobtrusive.min.js"); 
                    public static readonly string jquery_waypoints_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/jquery.waypoints.min.js"); 
                    public static readonly string js_cookie_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/js.cookie.js"); 
                    public static readonly string lightcase_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/lightcase.js"); 
                    public static readonly string main_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/main.js"); 
                    public static readonly string masonry_pkgd_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/masonry.pkgd.min.js"); 
                    public static readonly string PersianDatePicker_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/PersianDatePicker.js"); 
                    public static readonly string PersianDatePicker_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/PersianDatePicker.min.js"); 
                    public static readonly string slick_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/slick.min.js"); 
                    public static readonly string threesixty_min_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/threesixty.min.js"); 
                    public static readonly string touch_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/touch.js"); 
                    public static readonly string youtube_jquery_js = T4MVCHelpers.ProcessAssetPath("~/Content/js/youtube-jquery.js"); 
                }
            }
            public static class Assets
            {
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


