//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahanAraShop.Resourecs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JahanAraShop.Resourecs.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور فعلی وارد شده صحیح نمی باشد..
        /// </summary>
        public static string InCorrectPassword {
            get {
                return ResourceManager.GetString("InCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور اشتباه می باشد.
        /// </summary>
        public static string InvalidPassOrUserName {
            get {
                return ResourceManager.GetString("InvalidPassOrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور با کلمه عبور همخوانی ندارد..
        /// </summary>
        public static string IsNotSame {
            get {
                return ResourceManager.GetString("IsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اعتبارسنجی وارده شده اشتباه می باشد.
        /// </summary>
        public static string IsNotSameCode {
            get {
                return ResourceManager.GetString("IsNotSameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} فقط عدد می باشد..
        /// </summary>
        public static string JustNumber {
            get {
                return ResourceManager.GetString("JustNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} می بایست حداکثر {2} کاراکتر داشته باشد..
        /// </summary>
        public static string LimitCharacterRequired {
            get {
                return ResourceManager.GetString("LimitCharacterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا در وارد کردن شماره موبایل خود دقت کنید.
        /// </summary>
        public static string MobileEnter {
            get {
                return ResourceManager.GetString("MobileEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرکردن {0} الزامی است..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تلفن خود را بدرستی وارد کنید..
        /// </summary>
        public static string WrongCellPhoneEntered {
            get {
                return ResourceManager.GetString("WrongCellPhoneEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد..
        /// </summary>
        public static string WrongCode {
            get {
                return ResourceManager.GetString("WrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا آدرس ایمیل خود را بدرستی وارد کنید..
        /// </summary>
        public static string WrongEmailEntered {
            get {
                return ResourceManager.GetString("WrongEmailEntered", resourceCulture);
            }
        }
    }
}
